# Generated by Django 4.2.5 on 2023-09-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, null=True)),
                ('sheet', models.ImageField(upload_to='photosheets/')),
            ],
        ),
    ]
