services:
  sam_app:
    build:
      context: ./containerSAMAPP
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_URL=http://localhost:8000/
        - VITE_APP_PATH_PREFIX=sam/
    container_name: sam_app
    restart: always
    ports:
      - 3000:3000
    networks:
      - network
networks:
  network:
