# Generated by Django 5.0.3 on 2024-09-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(default='', max_length=100)),
                ('father_last_name', models.CharField(default='', max_length=50)),
                ('mother_last_name', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('major', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=50)),
                ('college', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=50)),
                ('degree', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='TechnicalPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=50)),
                ('nomination', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
