# Generated by Django 5.0.3 on 2024-09-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orcid', models.CharField(default='', max_length=19)),
                ('about', models.CharField(default='', max_length=500)),
                ('status', models.CharField(choices=[('pendiente', 'pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('utilizada', 'Utilizada')], default='pendiente')),
                ('username', models.CharField(default='')),
                ('email', models.EmailField(default='')),
                ('academic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='user.academic')),
            ],
        ),
    ]
