# Generated by Django 5.0.3 on 2024-10-26 17:04

from django.conf import settings
from django.db import migrations
from django.contrib.auth.models import User
from ..models import TechnicalPerson

def add_initial_data(apps, schema_editor):
    # Get model reference
    

    # Add records
    User.objects.create(
        username="alefchacon",
        password="pbkdf2_sha1$870000$eXsormkx40UrtgzxcA2Psy$D3Dai9H2xAyvDZzxSxqLlkAg4cE=",
        first_name="Alejandro",
        last_name="Chacon", 
        email="alefchacon@gmail.com"
    )

    TechnicalPerson.objects.create(
        fullname="Alejandro Chacon",
        position="Desarrollador",
        nomination="Desarrollador",
        user_id=1
    )

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_academic_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
