# Generated by Django 4.2.5 on 2023-09-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorSpecimen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.contributor')),
                ('contributor_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.contributorrole')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(default='', max_length=70)),
                ('class_specie', models.CharField(default='', max_length=70)),
                ('orden', models.CharField(default='', max_length=70)),
                ('family', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(default='', max_length=70)),
                ('epithet', models.CharField(default='', max_length=70)),
                ('subspecie', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_id', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('length_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('length_ear', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('length_paw', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('length_tail', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(max_length=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('number_embryos', models.IntegerField(blank=True, null=True)),
                ('colection_code', models.CharField(max_length=20)),
                ('colection_date', models.DateField()),
                ('hour', models.CharField(blank=True, max_length=5, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('contributors', models.ManyToManyField(blank=True, through='species.ContributorSpecimen', to='species.contributor')),
                ('specie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='species.specie')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates_cartesian_plane_x', models.FloatField()),
                ('coordinates_cartesian_plane_y', models.FloatField()),
                ('geographical_coordinates_x', models.FloatField()),
                ('geographical_coordinates_y', models.FloatField()),
                ('utm_region', models.CharField(max_length=4)),
                ('msnm_google', models.IntegerField()),
                ('altitude', models.IntegerField()),
                ('institute_code', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=150)),
                ('specific_location', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('specimen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimen', to='species.specimen')),
            ],
        ),
        migrations.AddField(
            model_name='contributorspecimen',
            name='specimen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.specimen'),
        ),
    ]
