# Generated by Django 4.2.5 on 2023-09-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributorrole',
            name='role',
            field=models.CharField(max_length=30, verbose_name='role'),
        ),
    ]
