# Generated by Django 5.0 on 2024-01-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_alter_location_specimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='scientific_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
