# Generated by Django 5.0.3 on 2024-09-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_remove_specimen_age_specimen_class_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='specie',
            name='specie_specie',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='specie',
            name='epithet',
            field=models.CharField(default='', max_length=210),
        ),
    ]
