# Generated by Django 5.0.3 on 2024-09-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_remove_specie_scientific_name_specie_specie_specie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='epithet',
        ),
    ]
