# Generated by Django 5.0.3 on 2024-09-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_remove_specie_epithet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
