# Generated by Django 5.0.3 on 2024-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_alter_specimen_length_ear_alter_specimen_length_paw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
