# Generated by Django 5.0.3 on 2024-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_alter_contributor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='kilometer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='colection_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specimen',
            name='nature',
            field=models.CharField(default='', max_length=50),
        ),
    ]
