# Generated by Django 5.0.3 on 2024-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_location_kilometer_specimen_colection_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
