# Generated by Django 5.0.3 on 2024-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_alter_contributor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specie',
            name='subspecie',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
