# Generated by Django 5.0.3 on 2024-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_alter_specie_subspecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='sex',
            field=models.CharField(max_length=5),
        ),
    ]
