# Generated by Django 5.1.3 on 2025-01-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0014_alter_specimen_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='reproductive_status',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
