# Generated by Django 5.1.3 on 2025-01-15 07:32
from ..models import ContributorRole
from django.db import migrations, models


def add_initial_data(apps, schema_editor):
    # Get model reference
    

    # Add records
    ContributorRole.objects.create(
        role="COLECTOR",
    )
    ContributorRole.objects.create(
        role="PREPARATOR",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_specimen_reproductive_status'),
    ]

    operations = [
        migrations.RunPython(add_initial_data)
    ]
