const SPECIMEN_KEYS = Object.freeze({
  catalog_id: "CAT_NUM",
  geographical_coordinates_x: "LW",
  geographical_coordinates_y: "LN",
  coordinates_cartesian_plane_x: "UTM_X",
  coordinates_cartesian_plane_y: "UTM_Y",
  class_specie: "CLASE",
  orden: "ORDEN",
  family: "FAMILIA",
  gender: "GENERO",
  specie_specie: "ESPECIE",
  subspecie: "SUBESPECIE",
  sex: "SEX",
  class_age: "EDAD",
  length_total: "LT",
  length_tail: "LC",
  length_paw: "LP",
  length_ear: "LO",
  weigth: "PESO",
  edo_rep: "EDO REP",
  number_embryos: "NO. EMB",
  country: "PAIS",
  state: "EDO",
  municipality: "MUNICIPIO",
  specific_location: "LOCALIDAD ESPECIFICA",
  kilometer: "Km",
  institute: "INSTITUCION",
  institute_code: "CODIGO_INSTITUCION",
  colection_code: "COD_COLECCION",
  utm_region: "REGION_UTM",
  msnm_google: "MSNM GOOGLE",
  altitude: "ALTITUD",
  colection_date: "FECHA",
  nature: "N.E",
  
  colection_number: "#COL",
  comment: "OBSERVACIONES _GRALES",
  colector_code: "COLECTOR",
  colector_name: "COLECTOR (NOMBRE)",
  preparator_code: "PREPARADOR",
  preparator_name: "PREPARADOR (nombre)",
}
)

export default SPECIMEN_KEYS;